export const LABEL_KEYS = Object.freeze({
  DASHBOARD: "DASHBOARD",
  ADMINS: "ADMINS",
  INVITATIONS: "INVITATIONS",
  METRICS_DASHBOARD: "METRICS_DASHBOARD",
  RESERVATIONS: "RESERVATIONS",
  CLIENTS: "CLIENTS",
  ROOMS: "ROOMS",
  INVOICES: "INVOICES",
  CMS_LANDING: "CMS_LANDING",
  AUDIT_LOG: "AUDIT_LOG",
});
